/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ShippingRole;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.Organization.ShippingOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Praneet
 */
public class ShippingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShippingWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    ShippingOrganization shippingOrganization;
    Business business;
    public ShippingWorkAreaJPanel(JPanel ucp,UserAccount userAccount,Organization organization,Business business) {
        initComponents();
        this.userProcessContainer = ucp;
        this.userAccount = userAccount;
        this.business = business;
        shippingOrganization = (ShippingOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderShippingRequest = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderShippingRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderShippingRequest.setText("Order Shipping Request>>");
        orderShippingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderShippingRequestActionPerformed(evt);
            }
        });
        add(orderShippingRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 134, 264, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orderShippingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderShippingRequestActionPerformed
        // TODO add your handling code here:
        OrderShippingStatusJPanel shpst = new OrderShippingStatusJPanel(userProcessContainer, userAccount, shippingOrganization, business);
        userProcessContainer.add("SupplierSubmitRequest", shpst);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderShippingRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton orderShippingRequest;
    // End of variables declaration//GEN-END:variables
}
