/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Business;

import Business.Person.PersonDirectory;
import Business.Order.MasterOrderCatalog;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Person.Customer;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Praneet
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
 PersonDirectory personDirectory;
    UserAccount ua;
  Business business;
  
SupplierOrganization organization;
    //CustomerDirectory customerDirectory;
//    MasterOrderCatalog masterOrderCatalog;
  //Person p;
Customer c;
    public CustomerWorkAreaJPanel(JPanel upc, PersonDirectory personDirectory, Business business, Customer c, UserAccount ua) {
        initComponents();
        
      //this.organization = organization;
        userProcessContainer = upc;
        this.personDirectory = personDirectory;
       // this.customerDirectory=customerDirectory;
        this.business= business;
        this.ua = ua;
        this.c = c;
               // ua.getPerson();

      
 System.out.println(c.getFirstName());
        
        //masterOrderCatalog = moc;
        
        
              customerNameTxt.setText(c.getFirstName());
      
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseProdJBtn = new javax.swing.JButton();
        orderHistory = new javax.swing.JButton();
        customerNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        trackOrder = new javax.swing.JButton();

        browseProdJBtn.setText("Browse Product Catalog>>");
        browseProdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseProdJBtnActionPerformed(evt);
            }
        });

        orderHistory.setText("Order History");
        orderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryActionPerformed(evt);
            }
        });

        customerNameTxt.setEnabled(false);
        customerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Hello");

        trackOrder.setText("Track Your Order ");
        trackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(browseProdJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trackOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(642, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(77, 77, 77)
                .addComponent(browseProdJBtn)
                .addGap(18, 18, 18)
                .addComponent(trackOrder)
                .addGap(15, 15, 15)
                .addComponent(orderHistory)
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseProdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseProdJBtnActionPerformed
        // TODO add your handling code here:
        BrowseProductJPanel browsep = new BrowseProductJPanel(userProcessContainer,  organization, c ,business.getMasterOrderCatalog(),personDirectory, ua, business);
        userProcessContainer.add("Browser Product",browsep);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                
    }//GEN-LAST:event_browseProdJBtnActionPerformed

    private void orderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryActionPerformed
        // TODO add your handling code here:
        CustomerOrderHistory coh = new CustomerOrderHistory(userProcessContainer, c, business.getMasterOrderCatalog());
        userProcessContainer.add("CustomerOrderHistory", coh);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_orderHistoryActionPerformed

    private void customerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTxtActionPerformed

    private void trackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackOrderActionPerformed
        // TODO add your handling code here:
        TrackOrderJPanel trackO = new TrackOrderJPanel(userProcessContainer, ua, business);
        userProcessContainer.add("TrackOrder",trackO);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_trackOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseProdJBtn;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderHistory;
    private javax.swing.JButton trackOrder;
    // End of variables declaration//GEN-END:variables
}
