 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole;

import Business.Business;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Customer;
import static Business.Organization.Organization.Type.Supplier;
import Business.Person.Person;
import Business.Person.PersonDirectory;

import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.UserAccessorProperty;

/**
 *
 * @author Praneet
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
   JPanel userProcessContainer;
   
//   UserAccountDirectory userAccountDirectory;
    Business business;
    public ManageUserAccountJPanel(JPanel upc, Business business) {
        initComponents();
        userProcessContainer = upc;
       
       this.business = business;
        
        populateUserAccountJTable();
        popOrganizationComboBox();
    }

    
    public void popOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : business.getOrganizationDirectory().getOrganizationList()) {
            organizationJComboBox.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        personJCombobox1.removeAllItems();
        
        for (Person p : organization.getPersonDirectory().getPersonList()){
            personJCombobox1.addItem(p);
        }
    }
    
    private void populateRoleComboBox(Organization organization){
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRoles()){
            roleJComboBox.addItem(role);
        }
    }
    
   private void populateUserAccountJTable()
    {
       
        DefaultTableModel dtm = (DefaultTableModel)userAccountJTable.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization : business.getOrganizationDirectory().getOrganizationList())
        {
            for(UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList())
            {
            Object row[] = new Object[4];
            row[0] = userAccount;
            row[1] = userAccount.getPerson().getFirstName();
            row[2] = userAccount.getRole();
            row[3] = userAccount.getStatus();
            dtm.addRow(row);
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountJTable = new javax.swing.JTable();
        addUserAccJBtn = new javax.swing.JButton();
        refreshJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        deactivateJBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        personJCombobox1 = new javax.swing.JComboBox();
        activeJRadioBtn = new javax.swing.JRadioButton();
        disableRadioButton2 = new javax.swing.JRadioButton();
        addUserAccJBtn1 = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manage User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, 334, 22));

        userAccountJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "First Name", "Role", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userAccountJTable);
        if (userAccountJTable.getColumnModel().getColumnCount() > 0) {
            userAccountJTable.getColumnModel().getColumn(0).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(1).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(2).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 375, 114));

        addUserAccJBtn.setText("Add Account");
        addUserAccJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccJBtnActionPerformed(evt);
            }
        });
        add(addUserAccJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 200, -1, -1));

        refreshJBtn.setText("Refresh");
        refreshJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJBtnActionPerformed(evt);
            }
        });
        add(refreshJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 200, -1, -1));

        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        deactivateJBtn1.setText("Deactivate User");
        deactivateJBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateJBtn1ActionPerformed(evt);
            }
        });
        add(deactivateJBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 200, -1, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 75, 24));

        jLabel3.setText("Status");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 75, 24));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 75, 24));

        jLabel5.setText("Role");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 75, 24));
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 98, -1));
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 98, -1));

        roleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJComboBoxActionPerformed(evt);
            }
        });
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 140, -1));

        jLabel6.setText("Person");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        personJCombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personJCombobox1ActionPerformed(evt);
            }
        });
        add(personJCombobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 140, -1));

        activeJRadioBtn.setText("Active");
        add(activeJRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        disableRadioButton2.setText("Disable");
        add(disableRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 147, -1));

        addUserAccJBtn1.setText("Add User Account");
        addUserAccJBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccJBtn1ActionPerformed(evt);
            }
        });
        add(addUserAccJBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, -1));

        jLabel7.setText("Organization");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addUserAccJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccJBtnActionPerformed
        // TODO add your handling code here:
//       AddUserAccountJPanel adduajp  = new AddUserAccountJPanel(userProcessContainer,organization, business);
//        userProcessContainer.add("ManageSupplierAdministrative", adduajp);
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_addUserAccJBtnActionPerformed

    private void deactivateJBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateJBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedRow= userAccountJTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Select a row to disable the user");
            return;
        }
        else
        {
            UserAccount ua = (UserAccount)userAccountJTable.getValueAt(selectedRow, 0);
            ua.setStatus("Disabled");
            JOptionPane.showMessageDialog(null, "User Account is deactivated");
            populateUserAccountJTable();
        }
    }//GEN-LAST:event_deactivateJBtn1ActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void refreshJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJBtnActionPerformed
        // TODO add your handling code here:
        populateUserAccountJTable();
    }//GEN-LAST:event_refreshJBtnActionPerformed

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed
        // TODO add your handling code here:
        //populatejcb();
    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void personJCombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personJCombobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personJCombobox1ActionPerformed

    private void addUserAccJBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccJBtn1ActionPerformed
        // TODO add your handling code here:
        boolean isContain =false;
        String usern = userNameTxt.getText();
        String password = passwordTxt.getText();
         Role role = (Role)roleJComboBox.getSelectedItem();
             Person p = (Person) personJCombobox1.getSelectedItem();

           String status;
            if (activeJRadioBtn.isSelected()) {
                status = "Active" ;
            } else {
                status = "Disabled";
            }

        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
            for(UserAccount userA : organization.getUserAccountDirectory().getUserAccountList())
             {
            if (usern.equals(userA.getUsername()))
            {
                isContain =true;

                break;

            }
        }
            if(isContain)
        {
            JOptionPane.showMessageDialog(null, "Username already exists");
           return;
           
        }
            else
            {
             organization.getUserAccountDirectory().createUserAccount(usern, password, p, role, status);
            }
        
        
       
       
    }//GEN-LAST:event_addUserAccJBtn1ActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeJRadioBtn;
    private javax.swing.JButton addUserAccJBtn;
    private javax.swing.JButton addUserAccJBtn1;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton deactivateJBtn1;
    private javax.swing.JRadioButton disableRadioButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox personJCombobox1;
    private javax.swing.JButton refreshJBtn;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable userAccountJTable;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
