/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesRole;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Praneet
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    SalesOrganization salesOrganization;
    Business business;
    
    public SalesWorkAreaJPanel(JPanel ucp,UserAccount userAccount,Organization organization,Business business) {
        initComponents();
        this.userProcessContainer = ucp;
        this.userAccount = userAccount;
        this.business = business;
        salesOrganization = (SalesOrganization)organization;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderRequest = new javax.swing.JButton();
        enrollmentRequest = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderRequest.setText("Order Requests>>");
        orderRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRequestActionPerformed(evt);
            }
        });
        add(orderRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 56, 260, -1));

        enrollmentRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enrollmentRequest.setText("Supplier Enrollment Request>>");
        enrollmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentRequestActionPerformed(evt);
            }
        });
        add(enrollmentRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 134, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orderRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRequestActionPerformed
        // TODO add your handling code here:
 SalesOrderProcessing saleop = new SalesOrderProcessing(userProcessContainer, userAccount, salesOrganization, business);
        userProcessContainer.add("SupplierSubmitRequest", saleop);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderRequestActionPerformed

    private void enrollmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentRequestActionPerformed
        // TODO add your handling code here:
        SalesEnrollRequest salesenre = new SalesEnrollRequest(userProcessContainer, userAccount, salesOrganization, business);
        userProcessContainer.add("SupplierSubmitRequest", salesenre);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_enrollmentRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollmentRequest;
    private javax.swing.JButton orderRequest;
    // End of variables declaration//GEN-END:variables
}
